---
title: "README file for Course Project"
author: "jip"
date: "Friday, August 22, 2014"
output: html_document
---

This README explains the purpose of this repo, which files you can find here and how the R script works in order to obtain the desired tidy data. 

## Purpose

The purpose of this work is to create a tidy dataset as course project for the coursera online course "Getting and Cleaning Data". The data used for this analysis represents data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

<http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones>


## Files in the repo

* README.md
* run_analysis.R
* CodeBook.md

## The R Script run_analysis.R

You should create one R script called run_analysis.R that does the following. 

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement. 
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names. 
5. Creates a second, independent tidy data set with the average of each variable for each activity and each subject. 

